// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// sfpca_fixed
Rcpp::List sfpca_fixed(Eigen::MatrixXd X, double lamu, double lamv, double alphau, double alphav, Eigen::MatrixXd Omegu, Eigen::MatrixXd Omegv, Eigen::VectorXd startu, Eigen::VectorXd startv, bool posu, bool posv, int maxit);
RcppExport SEXP _sfpca_sfpca_fixed(SEXP XSEXP, SEXP lamuSEXP, SEXP lamvSEXP, SEXP alphauSEXP, SEXP alphavSEXP, SEXP OmeguSEXP, SEXP OmegvSEXP, SEXP startuSEXP, SEXP startvSEXP, SEXP posuSEXP, SEXP posvSEXP, SEXP maxitSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type X(XSEXP);
    Rcpp::traits::input_parameter< double >::type lamu(lamuSEXP);
    Rcpp::traits::input_parameter< double >::type lamv(lamvSEXP);
    Rcpp::traits::input_parameter< double >::type alphau(alphauSEXP);
    Rcpp::traits::input_parameter< double >::type alphav(alphavSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type Omegu(OmeguSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type Omegv(OmegvSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type startu(startuSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type startv(startvSEXP);
    Rcpp::traits::input_parameter< bool >::type posu(posuSEXP);
    Rcpp::traits::input_parameter< bool >::type posv(posvSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    rcpp_result_gen = Rcpp::wrap(sfpca_fixed(X, lamu, lamv, alphau, alphav, Omegu, Omegv, startu, startv, posu, posv, maxit));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_sfpca_sfpca_fixed", (DL_FUNC) &_sfpca_sfpca_fixed, 12},
    {NULL, NULL, 0}
};

RcppExport void R_init_sfpca(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
